const width 		= window.innerWidth * .75;
const height 		= window.innerHeight * .75;
const X_START_POS 	= -500;
const Y_START_POS 	= -1800;
const NODE_COUNT 	= 13;
const NODE_RADIUS_MULT  = 3;
const CHARGE_STRENGTH 	= -500;
const CENTER_STRENGTH 	= 1;
const CENTER_POS 	= [width/2, height/2];
